# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_nbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_limited',
            name='bank',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
