# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_nbs', '0003_account_limited_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_limited',
            new_name='accountLimited',
        ),
    ]
