# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_nbs', '0004_auto_20170529_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountlimited',
            old_name='name',
            new_name='branch',
        ),
    ]
